config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

resources :conversations do
  resources :messages
end

  resources :tweets, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
   end

  resources :photos, only: [:index, :create, :edit, :update, :destroy]

  resources :topics do
	resources :comments
  end

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

  root 'top#index'
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
  <section class="function container-fluid">
    <div class="row">
    <h2>Function</h2>
      <div class="function-images">
        <div class="col-md-4 col-sm-4">
          <div class="function-image">
            <img src="<%= asset_path "twit.png"%>">
            <p><%=link_to "Tweet! (EXAM1)", tweets_path %></p>
          </div>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="function-image">
            <img src="<%= asset_path "insta.png"%>">
            <p><%=link_to "Insta! (EXAM2)", photos_path %></p>
          </div>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="function-image">
            <img src="<%= asset_path "FB.png"%>">
            <p><%=link_to "FB! (EXAM3)", topics_path %></p>
          </div>
        </div>
      </div>
    </div>
  </section>