config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

resources :conversations do
  resources :messages
end

  resources :tweets, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
   end

  resources :photos, only: [:index, :create, :edit, :update, :destroy]

  resources :topics do
	resources :comments
  end

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

  root 'top#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 500 }
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
        @topics = Topic.all
        if params[:back]
                @topic = Topic.new(topics_params)
        else
                @topic = Topic.new
        end
  end
  
# showアククションを定義します。入力フォームと一覧を表示するためインスタンスを2つ生成します。
  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end

def create
      @topic = Topic.new(topics_params)
      @topic.user_id = current_user.id
   if @topic.save
      redirect_to topics_path, notice: "投稿しました！"
 ###   NoticeMailer.sendmail_topic(@topic).deliver
   else
     @topics = Topic.all
     render 'index'
   end
  end

  def edit
   if @topic.user_id == current_user.id
   else
    redirect_to topics_path, notice: "編集出来ません（投稿ユーザで再度ログインして下さい"
   end
  end

  def update
   if @topic.user_id == current_user.id
    @topic.update(topics_params)
    if @topic.save
      redirect_to topics_path, notice: "編集しました！"
    else
     render 'edit'
    end
   else
    redirect_to topics_path, notice: "編集出来ません（投稿ユーザで再度ログインして下さい"
   end
  end

  def destroy
   if @topic.user_id == current_user.id
    @topic.destroy
    redirect_to topics_path, notice: "削除しました！"
   else
    redirect_to topics_path, notice: "削除出来ません（投稿ユーザで再度ログインして下さい）"
   end
  end


  private
    def topics_params
      params.require(:topic).permit(:title, :content, :user_id, :image, :image_cache, :remove_image)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :タイトル %>
  <%= f.text_field :title, class: 'form-control'  %>
  <br> 
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control'  %>
  <br>
  <%= f.submit 'Topic!', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/topics/edit.html.erb
<section class="function container-fluid">
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>Instaを編集する</h2>
<%= render 'form' %>
<%= link_to "一覧にもどる", topics_path %>
  </div>
</div>
</section>

app/views/topics/index.html.erb
  <section class="function container-fluid">
    <div class="row">
        <div class="col-md-6 col-sm-12">
          <h1>Topic投稿</h1>
          <%= render 'form' %>
        </div>

        <div class="col-md-6 col-sm-12">
        <h1>Topic一覧</h1>
         <div class="row">
         <% @topics.reverse_each do |topic| %>

          <div class="col-sm-12">
           <div class="tweet_col">
            <div class="tweet_col_content">
	      <% if topic.image? %>
	        <%= image_tag topic.image.url if topic.image? %>
	      <% end %><br>

	    <%= link_to topic_path(topic) do %>
	    <h4><strong><%= topic.title %></strong></h4>
	    <% end %>
            <p><%= topic.content %></p>
            <p><%= profile_img(topic.user) %><%= topic.user.name %></p>
            </div>
            <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-default btn-sm btn-success'  %>
            <%= link_to "削除", topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger'  %>
           </div>
          </div>
         <% end %>
         </div>
        </div>
    </div>

<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

</section>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="left"><%= profile_img(@topic.user) %><%= @topic.user.name %></p>
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @topic.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>